### ISSUE TITLE
Best way to GPUify nested loops over multi-dimensional arrays?

### ISSUE THREAD

**Issue by ali-ramadhan** [vchuravy/GPUifyLoops.jl#12]
I'm hoping to use GPUifyLoops.jl to rewrite the time stepping for [Oceananigans.jl](https://github.com/ali-ramadhan/Oceananigans.jl).

I'm just starting very small (basically building off the simple example with the `A[i] = 2*A[i]` kernel) but since my model works with 3D arrays I was wondering about the best way to iterate over arrays with sizes like 128×128×64. Here is what I have so far

```julia
using BenchmarkTools
using CUDAnative, CuArrays
using GPUifyLoops

@inline incmod1(a, n) = a == n ? 1 : a+1  # Wrap around indexing for i+1.
δx(f, Nx, i, j, k) = f[incmod1(i, Nx), j, k] - f[i, j, k]  # x-difference operator

function time_stepping_kernel(::Val{Dev}, f, δxf) where Dev
    @setup Dev
    
    Nx, Ny, Nz = size(f)
    @loop for i in (1:Nx; threadIdx().x)
        for k in 1:Nz, j in 1:Ny
            δxf[i, j, k] = δx(f, Nx, i, j, k)
        end
    end
    
    @synchronize
end

time_step!(A::Array, B::Array) = time_stepping_kernel(Val(:CPU), A, B)

function time_step!(A::CuArray, B::CuArray)
    @cuda threads=512 time_stepping_kernel(Val(:GPU), A, B)
end
```
but then this kernel is quite slow
```julia
julia> Nx, Ny, Nz = 128, 128, 64
julia> xc, yc = rand(Nx, Ny, Nz), rand(Nx, Ny, Nz);
julia> xg, yg = cu(rand(Nx, Ny, Nz)), cu(rand(Nx, Ny, Nz));

julia> @benchmark time_step!($xc, $yc)
BenchmarkTools.Trial: 
  memory estimate:  0 bytes
  allocs estimate:  0
  --------------
  minimum time:     5.830 ms (0.00% GC)
  median time:      5.843 ms (0.00% GC)
  mean time:        5.874 ms (0.00% GC)
  maximum time:     7.908 ms (0.00% GC)
  --------------
  samples:          851
  evals/sample:     1

julia> @benchmark time_step!($xg, $yg)
BenchmarkTools.Trial: 
  memory estimate:  288 bytes
  allocs estimate:  7
  --------------
  minimum time:     3.728 μs (0.00% GC)
  median time:      4.657 ms (0.00% GC)
  mean time:        4.344 ms (0.00% GC)
  maximum time:     4.663 ms (0.00% GC)
  --------------
  samples:          144
  evals/sample:     8
```
while I was hoping for a ~10x speed up compared to single-core CPU performance (see [this thread on Julia Discourse](https://discourse.julialang.org/t/writing-fast-stencil-computation-kernels-that-work-on-both-cpus-and-gpus/20200/2?u=polarizedpoutine)). I'm guessing it's slow because I'm only using a single block maybe? Is there a way to speed up `time_stepping_kernel` with GPUifyLoops.jl?

I also have a few questions:
1. Is it possible to use up as many threads as possible? I think broadcasting over CuArrays does this?
2. I should probably read up again on CUDA threads and blocks but is it possible to use `blockId`, `blockDim`, and `gridDim` with GPUifyLoops.jl?
3. I get a `CUDA error: too many resources requested for launch (code #701, ERROR_LAUNCH_OUT_OF_RESOURCES)` if I ask for too many threads (e.g. 1024). Googling around suggests that not enough registers are available. I assume I should probably be using blocks as well as threads to avoid jamming too many threads per block?

Thanks so much!

EDIT: Forgot to mention that this is with Julia 1.1, CUDA 9.2, and a Tesla V100.

**Comment by vchuravy** [comment]
For benchmarking use `CuArrays.@sync` to make sure that you are measuring the right thing. https://github.com/JuliaGPU/CuArrays.jl/pull/245

> Is it possible to use up as many threads as possible? I think broadcasting over CuArrays does this?

Absolutely you can use any kind of kernel launch configuration `threads=length(A)` or `threads=min(length(A), 256) blocks=...` that you want.

 > 3D arrays I was wondering about the best way to iterate over arrays with sizes

you probably want to setup a launch configuration like `thread=size(A)` and then use `threadIdx().x, threadIdx().y, threadIdx().z` in your kernel for `i, j, k`.

>  is it possible to use `blockId`, `blockDim`, and `gridDim` with GPUifyLoops.jl?

In ` @loop for i in (1:Nx; expr)` the expr can be anything that you want that calculates a single index. The only condition that is going to be imposed is that `expr in 1:Nx`. So you can use a combination of blocks and thread to calculate that. 
See https://github.com/jkozdon/nps_julialab_2019_Jan/blob/e55c10e38699f7961d2675b97b8b6a4681522ddd/vanilladeriv.jl#L249 for a more compilcated example.

> I assume I should probably be using blocks as well as threads to avoid jamming too many threads per block?

Jup!

**Comment by ali-ramadhan** [comment]
Awesome, thanks for the super fast reply! I'll see how far I can go with this and open a pull request with an example when it works.

I assume all the little kernels should be `@inline`d but maybe this is a micro-optimization

**Comment by jkozdon** [comment]
> For benchmarking use `CuArrays.@sync` to make sure that you are measuring the right thing. [JuliaGPU/CuArrays.jl#245](https://github.com/JuliaGPU/CuArrays.jl/pull/245)

So is it better to use `CuArrays.@sync` than something like

```
synchronize()
t1 = time_ns()
# do gpu stuff...
synchronize()
t2 = time_ns()
```

Looking at the `CuArrays.@sync` macro it's seems that you wouldn't get accurate timings with it unless you had that initial `synchronize()` since this would ensure that the device was quiet before executing the kernels.
