### ISSUE TITLE
Requesting an example program

### ISSUE THREAD

**Issue by willow-ahrens** [vchuravy/GPUifyLoops.jl#22]
An example program (say, applying the `log` function to an array) was requested at the clima monday morning meeting. @charleskawczynski was having some error running a similar kernel, perhaps he can file an issue on that as well?

**Comment by vchuravy** [comment]
https://github.com/vchuravy/GPUifyLoops.jl/blob/master/examples/simple.jl / https://juliagpu.gitlab.io/GPUifyLoops.jl/#Simple-1

@charleskawczynski please do open an issue

**Comment by lcw** [comment]
Please see the help documentation for `contextualize` for an example, i.e.,

```julia
?contextualize
```
