### ISSUE TITLE
Fix host hack for when CUDA not present

### ISSUE THREAD

**Issue by jkozdon** [vchuravy/GPUifyLoops.jl#3]
Here is the current hack:
```
const HAVE_CUDA = try
  using CUDAdrv
  using CUDAnative
  using CuArrays
  true
catch
  false
end
if !HAVE_CUDA
  macro cuStaticSharedMem(x...)
    :()
  end
  macro cuda(x...)
    :()
  end
end
```

**Comment by vchuravy** [comment]
GPUArrays has a good solution for this, that we should mimick (also for the `@cuda` macro)


- https://github.com/JuliaGPU/GPUArrays.jl/blob/58d462d9a72990daaddb99f2c74eedad0aced582/src/ondevice.jl#L22-L36
- https://github.com/JuliaGPU/CuArrays.jl/blob/599942e6d7baef535d6feef002c5eeec44492dce/src/gpuarray_interface.jl#L10-L13

**Comment by lcw** [comment]
With #20 and #40 merged the host hack is no longer need!
